# Generated by Django 4.2 on 2023-04-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_trainee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[(1, "Manager"), (2, "Mentor"), (3, "Trainee")],
                default=1,
                max_length=50,
            ),
        ),
    ]
