# Generated by Django 4.2 on 2023-04-20 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_rename_session_year_id_trainee_session_year_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mentor",
            old_name="adddress",
            new_name="address",
        ),
    ]
