# Generated by Django 4.2 on 2023-04-24 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_rename_adddress_mentor_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="session_year",
            name="session_name",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="trainee",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.course"
            ),
        ),
    ]
