# Generated by Django 4.2 on 2023-04-25 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_attendance_alter_trainee_session_year_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mentor_Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feedback", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mentor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.mentor"
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="attendance_report",
            name="attendace_id",
        ),
        migrations.RemoveField(
            model_name="attendance_report",
            name="trainee_id",
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.DeleteModel(
            name="Attendance_Report",
        ),
    ]
